require('plugins')
require('options')
require('treesitter-config')
require('lualine-config')
require('bufferline-config')
require('nvimtree-config')
require('telescope-config')
require('lsp')
vim.cmd('colorscheme lucidus')
